language: java
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

addons:
  sonarqube:
    branches:
      - master
      - issue23-reliability-rating

script:
  - jdk_switcher use oraclejdk8
  - sonar-scanner -X -Dsonar.host.url=https://sonarqube.com -Dsonar.login=$SONAR_GITHUB_TOKEN
